# Workflow's name
name: Hello World Workflow

# Los eventos que disparan el workflow son 'push' y 'pull_request'
on: [push, pull_request]

jobs:
  hola:
    # Especificar el 'runner' (VM: Vitual Machine) donde se ejecutará el job [hola]
    runs-on: ubuntu-latest
    # Definir los pasos que se ejecutarán en el job [hola]
    steps:
      - name: Hola Mundo
        run: echo "Hola, mundo desde GitHub Actions (eec)!"

      - name: touch file (crear archivo)
        run: touch hola.txt

      - name: Set text to the file
        run: echo "Hola mundo, by EEC." >> hola.txt

      - name: Read file content
        run: cat hola.txt
  
  other-job:
    runs-on: ubuntu-latest
    # Establecer relación de dependencia con el job [hola]
    # Esto significa que este job ('other-job') se ejecutará SOLO DESPUÉS de que el job [hola] haya finalizado correctamente
    needs: [hola]
    steps:
      - name: LS listar dirs y archivos
        run: ls -al