# Workflow's name
name: Hello World Workflow

# Los eventos que disparan el workflow son 'push' y 'pull_request'
# Utilizar activity-types y directivas para especificar con mayor detalle 
# cuándo se debe ejecutar el workflow
on:
  push:
    # Utilizar la directiva 'branches' para que el workflow SOLO se ejecute
    # cuando se haga un 'push' a la rama 'main'
    branches:
      - main
  
  pull_request:
    # El workflow se ejecutará cuando se cree un pull request hacia la rama 'main'
    branches:
      - main

jobs:
  hola:
    # Especificar el 'runner' (VM: Vitual Machine) donde se ejecutará el job [hola]
    runs-on: ubuntu-latest
    # Definir los pasos que se ejecutarán en el job [hola]
    steps:
      - name: Hola Mundo
        run: echo "Hola, mundo desde GitHub Actions (eec)!"

      - name: touch file (crear archivo)
        run: touch hola.txt

      - name: Set text to the file
        run: echo "Hola mundo, by EEC." >> hola.txt

      - name: Read file content
        run: cat hola.txt
  
  other-job:
    runs-on: ubuntu-latest
    # Establecer relación de dependencia con el job [hola]
    # Esto significa que este job ('other-job') se ejecutará SOLO DESPUÉS de que el job [hola] haya finalizado correctamente
    needs: [hola]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
      - name: LS listar dirs y archivos
        run: ls -al